name: feature-branch-checks
run-name: ${{ github.actor }} is running checks on feature branch
on:
  push:
    branches:
      - 'feature/**'

jobs:
  feature-branch-checks:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 5
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup
        id: setup
        run: |
          npm i -g zx
          zx ./scripts/setup.mjs
        env:
          ENV: DEV
          NAMESPACE: ${{ steps.short-sha.outputs.sha }}
      - name: Configure AWS Credentials for deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}
      - name: Lint
        run: npm run lint
      - name: Build
        run: zx ./scripts/build.mjs
        env:
          ENV: DEV
          NAMESPACE: ${{ steps.short-sha.outputs.sha }}
          STRIPE_API_SECRET: ${{ secrets.STRIPE_API_SECRET }}
          STRIPE_SIGNING_SECRET: ${{ secrets.STRIPE_SIGNING_SECRET }}
      - name: Deploy
        id: deploy
        run: zx ./scripts/deploy.mjs
        env:
          ENV: DEV
          NAMESPACE: ${{ steps.short-sha.outputs.sha }}
          STRIPE_API_SECRET: ${{ secrets.STRIPE_API_SECRET }}
          STRIPE_SIGNING_SECRET: ${{ secrets.STRIPE_SIGNING_SECRET }}
          MTN_COLLECTION_SUBSCRIPTION_KEY: ${{ secrets.MTN_COLLECTION_SUBSCRIPTION_KEY }}
          MTN_COLLECTION_API_USER: ${{ secrets.MTN_COLLECTION_API_USER }}
          MTN_COLLECTION_API_KEY: ${{ secrets.MTN_COLLECTION_API_KEY }}
          MTN_DISBURSEMENT_SUBSCRIPTION_KEY: ${{ secrets.MTN_DISBURSEMENT_SUBSCRIPTION_KEY }}
          MTN_DISBURSEMENT_API_USER: ${{ secrets.MTN_DISBURSEMENT_API_USER }}
          MTN_DISBURSEMENT_API_KEY: ${{ secrets.MTN_DISBURSEMENT_API_KEY }}
          MTN_TARGET_ENVIRONMENT: ${{ vars.MTN_TARGET_ENVIRONMENT }}
          MTN_PAYMENT_WEBHOOK_URL: ${{ vars.MTN_PAYMENT_WEBHOOK_URL }}
          MTN_DISBURSEMENT_WEBHOOK_URL: ${{ vars.MTN_DISBURSEMENT_WEBHOOK_URL }}
          KMS_KEY_ARN: ${{ vars.KMS_KEY_ARN }}
          SALESFORCE_CLIENT_SECRET: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
          SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
          SALESFORCE_URL_HOST: ${{ vars.SALESFORCE_URL_HOST }}
          SALESFORCE_OWNER_ID: ${{ secrets.SALESFORCE_OWNER_ID }}
          ENABLE_CACHE: ${{ vars.ENABLE_CACHE }}
          ENABLE_DYNAMODB_PROVISIONING: ${{ vars.ENABLE_DYNAMODB_PROVISIONING }}
          ORANGE_API_BASE_URL: ${{ vars.ORANGE_API_BASE_URL }}
          ORANGE_API_TOKEN_URL: ${{ vars.ORANGE_API_TOKEN_URL }}
          ORANGE_CLIENT_ID: ${{ secrets.ORANGE_CLIENT_ID }}
          ORANGE_X_AUTH_TOKEN: ${{ secrets.ORANGE_X_AUTH_TOKEN }}
          ORANGE_NOTIFY_URL=https: ${{ secrets.ORANGE_NOTIFY_URL }}
          ORANGE_PAYQAM_MERCHANT_PHONE: ${{ secrets.ORANGE_PAYQAM_MERCHANT_PHONE }}
          ORANGE_PAYQAM_PIN: ${{ secrets.ORANGE_PAYQAM_PIN }}
      - name: Destroy Deployment
        if: ${{ steps.deploy.outcome == 'success' && always() }}
        run: zx ./scripts/destroy.mjs
        env:
          ENV: DEV
          NAMESPACE: ${{ steps.short-sha.outputs.sha }}
      - name: Remove .npmrc
        if: always()
        run: rm -f ~/.npmrc
